import { NextResponse } from "next/server";
import { z } from "zod";
import { businessBriefSchema } from "@/lib/audit/types";
import { buildLiveIndonesianPromptPack } from "@/lib/audit/questions-id-live";
import { withPrimarySimilarBusiness } from "@/lib/audit/similar-businesses";

export const runtime = "nodejs";

// Spec 003 (work package A): the ten Indonesian questions are generated by one
// bounded no-search provider call resolved SERVER-SIDE, fail-closed to OpenCode
// Go serving gpt-5.6-luna per the founder-approved 2026-08-21 provider lock.
// The boundary never hard-fails: on provider/format failure it returns the
// deterministic Indonesian fallback pack (source "fallback", warnings
// ["fallback_used"]). The call is accounted server-side against a
// server-created budget; returned telemetry is folded into the session budget
// by the client.
const requestSchema = z.object({
  brief: businessBriefSchema,
});

export async function POST(request: Request) {
  try {
    const input = requestSchema.parse(await request.json());
    const result = await buildLiveIndonesianPromptPack({
      brief: withPrimarySimilarBusiness(input.brief),
    });
    return NextResponse.json(result);
  } catch (error) {
    return NextResponse.json(
      {
        error:
          error instanceof Error
            ? error.message
            : "Kami tidak dapat membuat pertanyaan audit.",
      },
      { status: 400 },
    );
  }
}
